spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true